# Generated by Django 3.0.5 on 2020-11-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('member_type', models.CharField(choices=[('Normal', 'Normal'), ('Honorable', 'Honorable'), ('Active', 'Active')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'feMale')], max_length=10)),
                ('id_no', models.CharField(max_length=25)),
            ],
        ),
    ]
